# Generated by Django 4.0.3 on 2022-03-30 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sslSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssl_title', models.CharField(max_length=100)),
                ('ssl_site', models.URLField()),
                ('ssl_desc', models.TextField()),
                ('ssl_cert_info', models.TextField()),
                ('ssl_create_date', models.DateField(blank=True, null=True)),
                ('ssl_expiry_date', models.DateField(blank=True, null=True)),
                ('ssl_last_check', models.DateField(blank=True, null=True)),
                ('ssl_status', models.IntegerField(default=1)),
                ('ssl_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
