# Generated by Django 4.0.3 on 2022-03-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sslapp', '0002_alter_sslsitemodel_ssl_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslsitemodel',
            name='ssl_create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sslsitemodel',
            name='ssl_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sslsitemodel',
            name='ssl_last_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
